<<<<<<< HEAD
name: ci-jupyter-pyspark

on:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - "*"
  #   paths:
  #     - jupyter/**
  #     - .github/workflows/jupyter.yml
  workflow_run:
    workflows: [ci-pyspark]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - base_image: inseefrlab/onyxia-pyspark:latest
            device_suffix: ""
          - base_image: inseefrlab/onyxia-pyspark:latest-gpu
            device_suffix: "-gpu"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: inseefrlab/onyxia-jupyter-pyspark
          tags: |
            # set latest tag for main branch
            type=raw,value=latest${{ matrix.device_suffix }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # propagate valid semver tags
            type=semver,pattern={{raw}}${{ matrix.device_suffix }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: jupyter/
          file: jupyter/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            DEVICE_SUFFIX=${{ matrix.device_suffix }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
=======
name: jupyter-pyspark

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pyspark]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-pyspark
      context: jupyter
      test: false
      push: true
      base_image: inseefrlab/onyxia-pyspark:latest
      base_image_gpu: inseefrlab/onyxia-pyspark:latest-gpu
>>>>>>> 0a3b76245e387c14cae7e1950e2ffb733abde599
